#!/usr/bin/env bash
# Read infra/config/oauth2-proxy-emails.txt → write a comma-separated WHITELIST
# line into the env file consumed by the oauth2-proxy compose service. Run on
# the VPS by .github/workflows/deploy.yml before `docker compose up -d
# --no-deps oauth2-proxy`.
#
# The output file is not committed (gitignored); it is regenerated on every
# deploy so the source of truth stays the .txt file.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SRC="$REPO_ROOT/infra/config/oauth2-proxy-emails.txt"
OUT="$REPO_ROOT/.env.oauth2-proxy"

if [ ! -f "$SRC" ]; then
  echo "render-whitelist: missing $SRC" >&2
  exit 1
fi

# Strip comments + blanks, trim, join with commas. Empty result is an error
# — an empty allowlist would lock everyone out, including Franck.
emails=$(grep -vE '^\s*(#|$)' "$SRC" | awk '{$1=$1; print}' | paste -sd, -)
if [ -z "$emails" ]; then
  echo "render-whitelist: $SRC produced an empty allowlist — aborting" >&2
  exit 1
fi

cat > "$OUT" <<EOF
# Generated by infra/scripts/render-whitelist.sh — DO NOT EDIT BY HAND.
# Source: infra/config/oauth2-proxy-emails.txt
WHITELIST=$emails
EOF

count=$(echo "$emails" | tr ',' '\n' | wc -l | tr -d ' ')
echo "render-whitelist: wrote $OUT ($count addresses)"
